### ISSUE TITLE
Why de-simple.py initialises ent_embs with dim s_emb_dim, but rel_embs with s+t_emb_dim?

### ISSUE THREAD

**Issue by anniezhi** [BorealisAI/de-simple#3]
Hi. Thank you for the open-sourced codes. 

In your paper, you mentioned that modeling relations with a static (rather than a diachronic) representation would suffice for decent performance. I perceive it as that you would embed the entities with temporal dims, and the relations with static dims. But in de-simple.py, the ent_embs are initialised with s_emb_dim, while the rel_embs are initialised with s_emb_dim + t_emb_dim. Could you please explain why so? Is there a conflict? 

Thank you.

**Comment by RishabGoel** [comment]
Hi @anniezhi,

Thanks for your interest and apologies for the delay in responding. There is no conflict. Please note that final embedding of an entity/relation(`emb_dim`) is `s_emb_dim` + `t_emb_sim`. From lines 20-23 we are initializing the static embeddings/features and for relations (as you also said) entire `emb_dim` is static. Thus, it is initialized as `s_emb_dim` + `t_emb_sim`. While for entities `s_emb_dim` is the dimension of the static features.
I hope this helps.
